export const STORAGE = {
  WEIGHT_UNIT:       'pullpush_weightUnit',
  FLOW_SOUNDS:       'pullpush_flowSounds',
  COUNTDOWN_STYLE:   'pullpush_countdownStyle',
  COUNTDOWN_LENGTH:  'pullpush_countdownLength',
  KEEP_SCREEN_ON:    'pullpush_keepScreenOn',
  ACTIVE_DATE:       'pullpush_activeDate',
  ACTIVE_TAB:        'pullpush_activeTab',
  ACTIVE_FLOW:       'pullpush_activeFlow',
  EDIT_MODE:         'pullpush_editMode',
  SELECTED_REST_DOW: 'pullpush_selectedRestDow',
  AUTOPLAY:          'pullpush_autoplay',
  LAST_ACTIVITY:     'pullpush_lastActivity',
  DELOAD_MODE:       'deload',
  DEV_ROLE_OVERRIDE: 'dev_role_override',
  THEME:             'theme',
  TIPS_GOAL:         'tips_goal',
  WEIGH_IN_DAY:      'weigh_in_day',
} as const
